default:
  INSTALLED_APPS:
    # ox
    - ox.apps.mails
    - ox.apps.content
    - ox.apps.files
    - ox.apps.tasks
    - ox.apps.auth
    - ox.apps.core
    # dependencies
    - django_tasks
    - django_tasks.backends.database
    - caps
    - django_filters
    - rest_framework
    # django
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.sites
    - django.contrib.messages
    - django.contrib.staticfiles

  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.middleware.locale.LocaleMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware

  # Internationalization
  # https://docs.djangoproject.com/en/5.0/topics/i18n/
  LANGUAGE_CODE: en
  LANGUAGES:
    - ["en", "English"]
    - ["fr", "French"]
    - ["de", "German"]
    - ["nl", "Dutch"]
    - ["es", "Spanish"]
  TIME_ZONE: UTC
  SITE_URL: http://localhost:8001/
  ROOT_URLCONF: "ox.urls"
  SITE_ID: 1

  TEMPLATES:
    - BACKEND: "django.template.backends.django.DjangoTemplates"
      DIRS:
        - "@format {this.BASE_DIR}/ox/templates"
      APP_DIRS: true,
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
          - django.template.context_processors.i18n

  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator

  STATIC_URL: /static/
  MEDIA_URL: /media/
  STATICFILES_FINDERS:
    - django.contrib.staticfiles.finders.FileSystemFinder
    - django.contrib.staticfiles.finders.AppDirectoriesFinder

  # Only used in dev
  MEDIA_ROOT: "@format {this.BASE_DIR}/static/media"

  LOGGING:
    version: 1
    disable_existing_loggers: false
    handlers:
        console:
            class: logging.StreamHandler
    root:
        handlers:
            - console
        level: INFO

  REST_FRAMEWORK:
    DEFAULT_FILTER_BACKENDS:
      - django_filters.rest_framework.DjangoFilterBackend
      - rest_framework.filters.SearchFilter
      - rest_framework.filters.OrderingFilter
    DEFAULT_PAGINATION_CLASS: ox.core.pagination.PageNumberPagination
    DEFAULT_RENDERER_CLASSES:
      - rest_framework.renderers.JSONRenderer
      - ox.core.renderers.AdminBrowsableAPIRenderer
    DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S %Z"
    PAGE_SIZE: 20
    DEFAULT_SCHEMA_CLASS: drf_spectacular.openapi.AutoSchema
    EXCEPTION_HANDLER: ox.core.exceptions.exception_handler

  SPECTACULAR_SETTINGS:
    COMPONENT_SPLIT_REQUEST: True
    ENUM_NAME_OVERRIDES: {}
    ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE: True
    SERVE_INCLUDE_SCHEMA: False
    # "POSTPROCESSING_HOOKS": [
    #    "drf_spectacular.hooks.postprocess_enum_name_with_choices"
    # ],

tests:
  PLUGINS_APPS:
    - dynaconf_merge_unique
    - tests.app

  # Paths are relative to project's root so pytest should be
  # run from there.
  STATIC_DIR: ./tests/static/
  MEDIA_ROOT: ./tests/static/.media

  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: "@format {this.BASE_DIR}/db.test.sqlite3"

  STATICFILES_FINDERS:
    dynaconf_merge:
        - ox.core.assets.finders.AssetsFinder

development:
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
  DEBUG: true

  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: "@format {this.BASE_DIR}/db.dev.sqlite3"

  STATICFILES_DIRS:
    - "@format {this.BASE_DIR}/static"
  
  STATICFILES_FINDERS:
    dynaconf_merge:
        - ox.core.assets.finders.AssetsFinder

production:
  DEBUG: false
  BASE_DIR: /srv/oxylus
  USE_X_FORWARDED_HOST: true
  SECURE_PROXY_SSL_HEADER: ["HTTP_X_FORWARDED_HOST", "https"]
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1

  STATIC_ROOT: "@format {this.BASE_DIR}/static"
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: "@format {env[POSTGRES_DB]}"
      USER: "@format {env[POSTGRES_USER]}"
      PASSWORD: "@format {env[POSTGRES_PASSWORD]}"
      HOST: "@format {env[POSTGRES_HOST]}"
      PORT: "@format {env[POSTGRES_PORT]}"

  OX:
    dynaconf_merge:
      SETTINGS_DIR: "/etc/oxylus/"
